#pragma once

#include "keymap.h"

#define CTL_TAB RCTL(KC_TAB)
#define CTL_Q RCTL(KC_Q)
#define CTL_W RCTL(KC_W)
#define CTL_E RCTL(KC_E)
#define CTL_R RCTL(KC_R)
#define CTL_T RCTL(KC_T)
#define CTL_Y RCTL(KC_Y)
#define CTL_U RCTL(KC_U)
#define CTL_I RCTL(KC_I)
#define CTL_O RCTL(KC_O)
#define CTL_P RCTL(KC_P)
#define CTL_AT RCTL(KC_LBRC)
#define CTL_LBRC RCTL(KC_RBRC)

#define CTL_A RCTL(KC_A)
#define CTL_S RCTL(KC_S)
#define CTL_D RCTL(KC_D)
#define CTL_F RCTL(KC_F)
#define CTL_G RCTL(KC_G)
#define CTL_H RCTL(KC_H)
#define CTL_J RCTL(KC_J)
#define CTL_K RCTL(KC_K)
#define CTL_L RCTL(KC_L)
#define CTL_SCLN RCTL(KC_SCLN)
#define CTL_COLN RCTL(KC_QUOT)
#define CTL_RBRC RCTL(KC_NUHS)

#define CTL_Z RCTL(KC_Z)
#define CTL_X RCTL(KC_X)
#define CTL_C RCTL(KC_C)
#define CTL_V RCTL(KC_V)
#define CTL_B RCTL(KC_B)
#define CTL_N RCTL(KC_N)
#define CTL_M RCTL(KC_M)
#define CTL_COMM RCTL(KC_COMM)
#define CTL_DOT RCTL(KC_DOT)
#define CTL_SLSH RCTL(KC_SLSH)
