#pragma once

#include "keymap.h"

#define RCT_TAB RCTL(KC_TAB)
#define RCT_Q RCTL(KC_Q)
#define RCT_W RCTL(KC_W)
#define RCT_E RCTL(KC_E)
#define RCT_R RCTL(KC_R)
#define RCT_T RCTL(KC_T)
#define RCT_Y RCTL(KC_Y)
#define RCT_U RCTL(KC_U)
#define RCT_I RCTL(KC_I)
#define RCT_O RCTL(KC_O)
#define RCT_P RCTL(KC_P)
#define RCT_AT RCTL(KC_LBRC)
#define RCT_LBRC RCTL(KC_RBRC)

#define RCT_A RCTL(KC_A)
#define RCT_S RCTL(KC_S)
#define RCT_D RCTL(KC_D)
#define RCT_F RCTL(KC_F)
#define RCT_G RCTL(KC_G)
#define RCT_H RCTL(KC_H)
#define RCT_J RCTL(KC_J)
#define RCT_K RCTL(KC_K)
#define RCT_L RCTL(KC_L)
#define RCT_SCLN RCTL(KC_SCLN)
#define RCT_COLN RCTL(KC_QUOT)
#define RCT_RBRC RCTL(KC_NUHS)

#define RCT_Z RCTL(KC_Z)
#define RCT_X RCTL(KC_X)
#define RCT_C RCTL(KC_C)
#define RCT_V RCTL(KC_V)
#define RCT_B RCTL(KC_B)
#define RCT_N RCTL(KC_N)
#define RCT_M RCTL(KC_M)
#define RCT_COMM RCTL(KC_COMM)
#define RCT_DOT RCTL(KC_DOT)
#define RCT_SLSH RCTL(KC_SLSH)

#define RCT_SP RCTL(KC_SPC)
#define RCT_ENT RCTL(KC_ENT)